### ISSUE TITLE
KeyError: 'request_id'

### ISSUE THREAD

**Issue by albert-kam** [dabapps/django-log-request-id#32]
Hi, i followed strictly the readme on how to install, and i found this error:

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/logging/__init__.py", line 622, in format
    s = self.formatMessage(record)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/logging/__init__.py", line 591, in formatMessage
    return self._style.format(record)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/logging/__init__.py", line 433, in format
    return self._fmt % record.__dict__
KeyError: 'request_id'
Call stack:
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 154, in handle
    handler.run(self.server.get_app())
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/contrib/staticfiles/handlers.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/contrib/auth/views.py", line 65, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/moonblade/devel/python/miniconda3/lib/python3.7/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/home/moonblade/devel/java/eclipse_workspace/Daruma/daruma/apps/authentication/views.py", line 193, in get_context_data
    logger.debug("logger CCTV Started in login process!")
Message: 'logger CCTV Started in login process!'
Arguments: ()

```

I wonder what i missed ? 
Please help.

**Comment by albert-kam** [comment]
Turns out i forgot to include the filter within the handler. 
Sorry for the trouble !
