### ISSUE TITLE
Can not install version 1.4.0 on python3.7.4 (python3.6, no problem)

### ISSUE THREAD

**Issue by chongjing001** [dabapps/django-log-request-id#39]
`(venv37) tj001@Ubantu18:~/code/lengine-service$ python -m pip install django-log-request-id`
```
Collecting django-log-request-id
  Using cached https://files.pythonhosted.org/packages/17/2f/d283eacfc9a149f65298eb0a4eec6d85a9589e15e9f11468f69ab183a250/django-log-request-id-1.4.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/tj001/env/venv37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8d592g5r/django-log-request-id/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8d592g5r/django-log-request-id/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8d592g5r/django-log-request-id/pip-egg-info
         cwd: /tmp/pip-install-8d592g5r/django-log-request-id/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/tj001/env/venv37/lib/python3.7/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/tj001/env/venv37/lib/python3.7/site-packages/setuptools/dist.py", line 36, in <module>
        from setuptools import windows_support
      File "/home/tj001/env/venv37/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by chongjing001** [comment]
sorry，virtual machine has this problem

**Comment by RealOrangeOne** [comment]
@chongjing001 to confirm, this isn't an issue with `django-log-request-id`?

**Comment by chongjing001** [comment]
There is no problem installing other packages.
```
(venv37) tj001@Ubantu18:~/env$ pip install django -i https://pypi.douban.com/simple
Looking in indexes: https://pypi.douban.com/simple
Collecting django
  Downloading https://pypi.doubanio.com/packages/6a/23/08f7fd7afdd24184a400fcaebf921bd09b5b5235cbd62ffa02308a7d35d6/Django-3.0.1-py3-none-any.whl (7.4MB)
     |████████████████████████████████| 7.4MB 276kB/s 
Requirement already satisfied: asgiref~=3.2 in ./venv37/lib/python3.7/site-packages (from django) (3.2.3)
Requirement already satisfied: sqlparse>=0.2.2 in ./venv37/lib/python3.7/site-packages (from django) (0.3.0)
Requirement already satisfied: pytz in ./venv37/lib/python3.7/site-packages (from django) (2019.3)
Installing collected packages: django
Successfully installed django-3.0.1
```
